/**
 * Vietnamese localization for the FIXED deterministic strings inside an analysis
 * result_json — score-breakdown labels/explanations (mapped by stable `key`) and
 * the limitation/disclaimer sentences (exact-match).
 *
 * Interpolated prose (the summary, missing-skill reasons/suggestions, improvement
 * actions, interview-prep questions, and learning-roadmap detail) is generated by
 * the backend analysis pipeline with the skill/JD values inlined; localizing that
 * requires threading a language through that pipeline and is a separate follow-up.
 * Technical terms / skill names are never translated.
 */

const BREAKDOWN_LABELS = {
  skill_match: 'Mức độ khớp kỹ năng',
  responsibility_match: 'Mức độ khớp trách nhiệm',
  experience_level: 'Mức kinh nghiệm',
  project_relevance: 'Mức độ liên quan dự án',
  cv_quality: 'Chất lượng CV',
};

const BREAKDOWN_EXPLANATIONS = {
  skill_match: 'Mức độ bao phủ các nhóm kỹ năng bắt buộc và ưu tiên của JD được tìm thấy trong CV đã phân tích.',
  responsibility_match: 'Mức độ tương đồng giữa các gạch đầu dòng trong CV và phần trách nhiệm trong JD.',
  experience_level: 'Ước lượng mức độ phù hợp về thâm niên từ các tín hiệu thời gian trong CV đã phân tích.',
  project_relevance: 'Mức độ liên quan và mật độ của các gạch đầu dòng về dự án hoặc kinh nghiệm.',
  cv_quality: 'Chất lượng phân tích, thông tin liên hệ, số liệu và các gạch đầu dòng theo hướng hành động.',
};

// Exact English → Vietnamese for the fixed limitation/disclaimer sentences.
const LIMITATIONS = {
  'This analysis estimates CV-to-JD fit only and does not guarantee any hiring outcome.':
    'Phân tích này chỉ ước lượng mức độ phù hợp giữa CV và JD và không đảm bảo bất kỳ kết quả tuyển dụng nào.',
  'Missing evidence means support was not found in the parsed CV, not that the candidate definitely lacks the skill.':
    'Thiếu bằng chứng nghĩa là không tìm thấy hỗ trợ trong CV đã phân tích, chứ không phải ứng viên chắc chắn thiếu kỹ năng đó.',
  'Do not invent skills, experience, projects, metrics, or responsibilities based on these suggestions.':
    'Không bịa đặt kỹ năng, kinh nghiệm, dự án, số liệu hay trách nhiệm dựa trên các gợi ý này.',
  'Parser confidence is based on extracted text quality and may miss content from scanned or image-heavy files.':
    'Độ tin cậy của bộ phân tích dựa trên chất lượng văn bản trích xuất và có thể bỏ sót nội dung từ file scan hoặc nhiều hình ảnh.',
};

export function localizeBreakdownLabel(key, fallback) {
  return BREAKDOWN_LABELS[key] || fallback || key || '';
}

export function localizeBreakdownExplanation(key, fallback) {
  return BREAKDOWN_EXPLANATIONS[key] || fallback || '';
}

export function localizeLimitation(text) {
  return LIMITATIONS[text] || text || '';
}
